# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ClientCredentialResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, access_token: str=None, token_type: str=None, expires_in: int=None, refresh_token: str=None, scope: str=None):  # noqa: E501
        """ClientCredentialResponse - a model defined in Swagger

        :param access_token: The access_token of this ClientCredentialResponse.  # noqa: E501
        :type access_token: str
        :param token_type: The token_type of this ClientCredentialResponse.  # noqa: E501
        :type token_type: str
        :param expires_in: The expires_in of this ClientCredentialResponse.  # noqa: E501
        :type expires_in: int
        :param refresh_token: The refresh_token of this ClientCredentialResponse.  # noqa: E501
        :type refresh_token: str
        :param scope: The scope of this ClientCredentialResponse.  # noqa: E501
        :type scope: str
        """
        self.swagger_types = {
            'access_token': str,
            'token_type': str,
            'expires_in': int,
            'refresh_token': str,
            'scope': str
        }

        self.attribute_map = {
            'access_token': 'access_token',
            'token_type': 'token_type',
            'expires_in': 'expires_in',
            'refresh_token': 'refresh_token',
            'scope': 'scope'
        }
        self._access_token = access_token
        self._token_type = token_type
        self._expires_in = expires_in
        self._refresh_token = refresh_token
        self._scope = scope

    @classmethod
    def from_dict(cls, dikt) -> 'ClientCredentialResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The clientCredentialResponse of this ClientCredentialResponse.  # noqa: E501
        :rtype: ClientCredentialResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_token(self) -> str:
        """Gets the access_token of this ClientCredentialResponse.

        access token povided by Authorization service  # noqa: E501

        :return: The access_token of this ClientCredentialResponse.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this ClientCredentialResponse.

        access token povided by Authorization service  # noqa: E501

        :param access_token: The access_token of this ClientCredentialResponse.
        :type access_token: str
        """
        if access_token is None:
            raise ValueError("Invalid value for `access_token`, must not be `None`")  # noqa: E501

        self._access_token = access_token

    @property
    def token_type(self) -> str:
        """Gets the token_type of this ClientCredentialResponse.

        token type, must be Bearer.  # noqa: E501

        :return: The token_type of this ClientCredentialResponse.
        :rtype: str
        """
        return self._token_type

    @token_type.setter
    def token_type(self, token_type: str):
        """Sets the token_type of this ClientCredentialResponse.

        token type, must be Bearer.  # noqa: E501

        :param token_type: The token_type of this ClientCredentialResponse.
        :type token_type: str
        """
        allowed_values = ["Bearer"]  # noqa: E501
        if token_type not in allowed_values:
            raise ValueError(
                "Invalid value for `token_type` ({0}), must be one of {1}"
                .format(token_type, allowed_values)
            )

        self._token_type = token_type

    @property
    def expires_in(self) -> int:
        """Gets the expires_in of this ClientCredentialResponse.

        expiration period in seconds.  # noqa: E501

        :return: The expires_in of this ClientCredentialResponse.
        :rtype: int
        """
        return self._expires_in

    @expires_in.setter
    def expires_in(self, expires_in: int):
        """Sets the expires_in of this ClientCredentialResponse.

        expiration period in seconds.  # noqa: E501

        :param expires_in: The expires_in of this ClientCredentialResponse.
        :type expires_in: int
        """

        self._expires_in = expires_in

    @property
    def refresh_token(self) -> str:
        """Gets the refresh_token of this ClientCredentialResponse.

        refresh token povided by Authorization service  # noqa: E501

        :return: The refresh_token of this ClientCredentialResponse.
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token: str):
        """Sets the refresh_token of this ClientCredentialResponse.

        refresh token povided by Authorization service  # noqa: E501

        :param refresh_token: The refresh_token of this ClientCredentialResponse.
        :type refresh_token: str
        """

        self._refresh_token = refresh_token

    @property
    def scope(self) -> str:
        """Gets the scope of this ClientCredentialResponse.

        application defined scope.  # noqa: E501

        :return: The scope of this ClientCredentialResponse.
        :rtype: str
        """
        return self._scope

    @scope.setter
    def scope(self, scope: str):
        """Sets the scope of this ClientCredentialResponse.

        application defined scope.  # noqa: E501

        :param scope: The scope of this ClientCredentialResponse.
        :type scope: str
        """

        self._scope = scope
